### PR TITLE
Add .npmignore #927

### PR DESCRIPTION
**Pull request by AObuchow**
Add .npmignore to prevent `out` folder from being ignored during `npm pack`

### CODE REVIEW

**Comment by roblourens** [comment]
Can you explain what this is for?

**Comment by AObuchow** [comment]
@roblourens This commit is to simplify the integration (packaging) of the Chrome debugger into other IDE's that support the Debug Adapter Protocol. 

Currently, I am working on integrating the Chrome debugger into Eclipse.
For Eclipse, the packaging process currently involves downloading the VSCode extension and then using `npm pack` on the Extension directory. 

Unfortunately, `npm pack` ignores everything on the `.gitignore` unless a `.npmignore` is provided. As a result, the files in the `out` directory were getting left out when running `npm pack`.

**Comment by roblourens** [comment]
Have you considered using `vsce pack` instead? That might work better since it will use the same logic that we actually use to publish this to the app store. I am worried that since I am not using this, I could end up breaking you.

**Comment by mickaelistria** [comment]
For all other language servers and debug adapters (coming from VSCode or VSCode extensions), we're using npm which is standard enough and does a good job at de-duplicating dependencies. Like most people our community has basic enough knowledge of npm to make it work, but doesn't have any knowledge of `vsce`, so it'd be extremely easier to the project and its community if we could solely rely on npm.

**Comment by roblourens** [comment]
Ok, I can merge this but know that I don't offer any guarantees about how well this will work with npm.

Also please don't publish it to npm under the `vscode-chrome-debug` name unless it is under an  organization name or something. (I would just rather leave the name free for me to own in case I do decide to publish it to npm some day)

**Pull request merged**
