### PR TITLE
Add animated GIF to README

### PR DESCRIPTION
**Pull request by auchenberg**

### CODE REVIEW

**Comment by paulirish** [comment]
Looks good!

**Comment by danmosemsft** [comment]
This particular gif does not appear to render in IE or Edge, only in Chrome. I'll open a bug.

**Comment by auchenberg** [comment]
Interesting. Renders fine in Blink, Webkit and Gecko.

**Comment by danmosemsft** [comment]
It's because GitHub is serving the gif with  "X-Content-Type-Options": "nosniff"  and Content-Type: application/octet-stream and Chrome is ignoring that. I'm sure there's lots of history here I'm unaware of so I'll ask internally. 
More usefully -- how can we get GitHub to serve this as image/gif, I see it does that with [some others](https://github.com/Flipboard/FLAnimatedImage/blob/master/images/flanimatedimage-demo-player.gif)

**Comment by danmosemsft** [comment]
OK, I've done enough reading of Chrome and Mozilla archives to see that this is something under debate. And since I'm not on the IE/Edge team and don't know much about HTTP I'll let them continue that debate. :)

So how do we make GitHub serve it right?

**Comment by danmosemsft** [comment]
I can't take this any further this weekend and I'm gone next week. Kenneth - tag!

**Comment by auchenberg** [comment]
@danmosemsft Using rawgit.com seems to serve the correct mime type. Fixed in https://github.com/Microsoft/vscode-chrome-debug/commit/085b88c936bbc0d012b37444f1f421308d325b74.

**Comment by mislav** [comment]
I'm glad to see that you worked around your issue. GitHub intentionally doesn't serve various file type with the correct `Content-type` to prevent hotlinking and various XSS vectors. Therefore, hotlinking an image from a git repo, even when it's from the same repo, in a manner like this `Demo` isn't designed to work, and only accidentally works on some browsers due to them not respecting `Content-type`.

**Pull request merged**
