### PR TITLE
Fix typo: sourceMapOverrides -> sourceMapPathOverrides.

### PR DESCRIPTION
**Pull request by lijunle**
Fix typo: sourceMapOverrides -> sourceMapPathOverrides.

### CODE REVIEW

**Comment by nojvek** [comment]
This is purely a documentation change right? 

LGTM.

**Comment by lijunle** [comment]
Yes. I copied the code snippet to VS code. It draw a green underline on it. In the paragraph above the code snippet, the option has a different name.

**Comment by nojvek** [comment]
It seems your edit is adding some unicode emoticons.  Might want to fix that.

```
"sourceMapOverrides": {
    "webpack:///*": "${webRoot}/*", // Example: "webpack:///src/app.js" -> "/users/me/project/src/app.js"
    "meteor://💻app/*": "${webRoot}/*" // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```

**Comment by lijunle** [comment]
It was originally there, I don't touch it.

**Comment by lijunle** [comment]
@roblourens the doc has some Unicode chars in the code snippet. Is that expected?

**Comment by roblourens** [comment]
Thanks!

**Comment by lijunle** [comment]
@roblourens How about the Unicode emoji - `💻`? Are we going to keep them?

**Comment by roblourens** [comment]
Yeah it's supposed to be there.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/transformers/sourceMapTransformer.ts#L25

**Comment by lijunle** [comment]
Aha! It looks crazy to have emoji in a path. :smiley:

**Pull request merged**
